# Generated by Django 4.1.2 on 2022-10-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BussInfo',
            fields=[
                ('buss_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buss_name', models.CharField(max_length=50)),
                ('buss_logo', models.ImageField(upload_to=None)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=50)),
                ('location1', models.CharField(max_length=70)),
                ('location2', models.CharField(blank=True, max_length=70)),
                ('location3', models.CharField(blank=True, max_length=70)),
                ('location4', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='KeyDecisionMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('signature', models.ImageField(upload_to=None)),
                ('buss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bussinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('signature', models.ImageField(upload_to=None)),
                ('buss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bussinfo')),
            ],
        ),
    ]
