# Generated by Django 4.1.2 on 2022-10-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BussInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_aggrement', models.DateField()),
                ('buss_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=50)),
                ('location1', models.CharField(max_length=70)),
                ('location2', models.CharField(blank=True, max_length=70)),
                ('location3', models.CharField(blank=True, max_length=70)),
                ('location4', models.CharField(blank=True, max_length=70)),
                ('keydecider_name', models.CharField(max_length=30)),
                ('keydecider_title', models.CharField(max_length=30)),
                ('keydecider_email', models.CharField(max_length=30)),
                ('keydecider_signature', models.CharField(max_length=30)),
                ('envmanager_name', models.CharField(max_length=30)),
                ('envmanager_title', models.CharField(max_length=30)),
                ('envmanager_email', models.CharField(max_length=30)),
                ('envmanager_signature', models.CharField(max_length=30)),
                ('otherresp_person_name', models.CharField(blank=True, max_length=30)),
                ('otherresp_person_title', models.CharField(blank=True, max_length=30)),
                ('otherresp_person_email', models.CharField(blank=True, max_length=30)),
                ('otherresp_person_signature', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvCompOblig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_oblig_name', models.CharField(max_length=50)),
                ('comp_oblig_description', models.TextField()),
                ('env_comm_option', models.CharField(choices=[('suggestion', 'suggestion'), ('positive feedback', 'positive feedback'), ('complaints', 'complaints'), ('requests', 'requests')], max_length=50)),
                ('env_comm_description', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bussinfo')),
            ],
        ),
    ]
