# Generated by Django 4.1.2 on 2022-10-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvComm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_option', models.CharField(choices=[('suggestion', 'suggestion'), ('positive feedback', 'positive feedback'), ('complaints', 'complaints'), ('requests', 'requests')], max_length=50)),
                ('description', models.TextField()),
                ('buss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bussinfo')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agreementdoc')),
            ],
        ),
    ]
