# Generated by Django 4.1.2 on 2022-10-25 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_1', models.CharField(max_length=50)),
                ('aspect_1', models.CharField(max_length=50)),
                ('impact_1', models.CharField(max_length=50)),
                ('activity_2', models.CharField(max_length=50)),
                ('aspect_2', models.CharField(max_length=50)),
                ('impact_2', models.CharField(max_length=50)),
                ('activity_3', models.CharField(max_length=50)),
                ('aspect_3', models.CharField(max_length=50)),
                ('impact_3', models.CharField(max_length=50)),
                ('activity_4', models.CharField(max_length=50)),
                ('aspect_4', models.CharField(max_length=50)),
                ('impact_4', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
